POST https://piana-sms.herokuapp.com/guest/sms/delivery
content-type: application/x-www-form-urlencoded;charset=UTF-8

from=0912&to=12341&message=sdjbnu&messageid=1
###
POST localhost:8080/guest/sms/delivery
content-type: application/x-www-form-urlencoded;charset=UTF-8

from=09391366128&to=10006600060060&message=12345678&messageid=3
###
POST localhost:8080/user/sms
content-type: application/json
Authorization: Basic dXNlcjpBc2FkTWFzYWRAMTM2Ng==

{
  "mobile": "09391366128"
}
###